export default {
    id: 0,
    name: "",
    email: "",
    surname: "",
    fullname: "",
    birthday: "",
    schoolNo: "",
    h_phone: "",
    gsm: "",
    tc: "",
    address: "",
    isActive: true,
    s_status: {'school': false, 'activity': false, 'sporclub': false},
    file: null,
    file_id: 0,
    file_path: "",
    gender: 0,
    family: 1,
    school_id: 0,
    class_id: 0,
    lesson_id: 0,
    branch_id: 0,
    activity_id: 0,
    period_id: 0,
    grade_id: 0,
    club_id: 0,
    team_id: 0,
    cbranch_id:0,
    actiontype: 0, // yeni kayıt veya güncelleme 0 yeni kayıt
}