/*ACTION_NAMES*/

export const FETCH_USERS = 'fetchUsers'
export const CREATE_USERS = 'createUsers'
export const DELETE_USERS = 'deleteUsers'
export const UPDATE_USERS = 'updateUsers'
export const FETCH_ALL_USERS = 'fetchAllUsers'
export const SHOW_USER = 'showUser'
export const FETCH_USER_SCHOOL = 'getUserSchoolU'
export const FETCH_USER_LESSON = 'getUserLessonU'

export const FETCH_ACTIVITY_PROGRAM = 'getUserActivityProgram'
export const FETCH_ALL_USER_APROGRAM = 'fetchAllUserActivityProgram'
export const FETCH_ALL_USER_PROGRAM = 'fetchAllUserSchoolProgram'
export const FETCH_PERSONEL_STUDENTS = 'fetchPersonStudents'
export const FETCH_PERSON_CLUB_TEAM = 'fetchPersonClubTeam'
export const FETCH_PERSONS_CLUB = 'fetchPersonClub'
export const FETCH_ALL_PERSONS_EXPORT_EXCEL = 'fetchAllPersonExportExcel'
export const FETCH_PERSONS = 'fetchPersons'
export const DELETE_PERSONS = 'deletePerson'
export const UPDATE_PERSONS = 'updatePerson'
export const UPDATE_PERSON_IMAGE = 'updatePersonImage'
export const UPDATE_PERSON_STATUS = 'updatePersonStatus'
export const FETCH_USER_CLASES_SCHOOL = 'getUserSchoolClasesU'
export const FETCH_USER_CLASES_BRANCHES = 'getUserSchoolClasesBranchesU'
export const FETCH_USER_PROGRAM = 'getUserSchoolProgram'
export const FETCH_ALL_SCHOOL_PERSON = 'fetchAllSchoolPerson'
export const FETCH_ALL_USER_APROGRAM_TODAY = 'fetchAllActivityUserToday'
export const FETCH_USER_PROGRAM_TODAY = 'getUserSchoolProgramToday'
export const FETCH_USER_SPORCLUB_PROGRAM = 'fetchUserSporClubProgram'
export const FETCH_SCLUB_PROGRAM_D = 'fetchUserSporClubProgramD'
export const FETCH_ALL_USERSSEARCH = 'fetchAllUsers'
export const FETCH_ALL_USER_AND_STUDENT = 'fetchAllUserAndStudent'
export const FETCH_USER_WITH_LESSON = 'fetchUserWithLesson'
export const FETCH_USER_STUDENTS = 'fetchUserStudents'
/*GETTER_NAMES*/
export const GET_USER_STUDENTS = 'getUserStudents'
export const GET_USER_SPORCLUB_PROGRAM_D = 'getUserSporClubProgramD'
export const GET_USER_SPORCLUB_PROGRAM = 'getUserSporClubProgram'
export const GET_USERS = 'getUsers'
export const GET_USERS_HEADER = 'getUsersHeader'
export const GET_USER_PROGRAM = 'getUserPrograms'
export const GET_ACTIVITY_USER_PROGRAM = 'getActivityUserPrograms'

/*MUTATIONS_NAMES*/
export const SET_USER_STUDENTS = 'setUserStudents'
export const SET_USER_SPORCLUB_PROGRAM_D = 'setUserSporClubProgramD'
export const SET_USER_SPORCLUB_PROGRAM = 'setUserSporClubProgram'
export const SET_USER_PROGRAMS_ALL = 'setUserPrograms'
export const SET_USERS = 'setUsers'
export const SET_USER_ACT_PROGRAMS = 'setActivityUserPrograms'
