/*ACTION_NAMES*/

export const FETCH_DISCONT = 'fetchDıscont'
export const CREATE_DISCONT = 'createDıscont'
export const DELETE_DISCONT = 'deleteDıscont'
export const UPDATE_DISCONT = 'UpdateDıscont'
export const FETCH_ALL_DISCONT = 'fetchAllDıscont'
export const FETCH_SELECTEDPROGRAM_STUDENTS = 'fetchSelectedProgramStudents'
export const FETCH_ASELECTEDPROGRAM_STUDENTS = 'fetchASelectedProgramStudents'
export const FETCH_GETSTUDENT_DISCONT = 'fetchStudentDiscont'
export const FETCH_STUDENTS_D = 'fetchStudentdD'
export const FETCH_STUDENT_FOR_D = 'fetchStudentForD'
export const FETCH_STUDENT_DISCONT_STATUS = 'fetchStudentDStatus'
export const FETCH_ACTIVITY_GRADES_D = 'fetchActivityGradesD'
export const FETCH_ACTIVITY_GRADES_DP = 'fetchAcitivityGraderPeriods'
export const FETCH_GETSTUDENTS_DISCONTS_GP = 'fetchDiscontStudentGP'
export const FETCH_STUDENTFOR_DISCONT_A = 'fetchStundetDiscontForA'
export const FETCH_ACTDIS_STUDENT = 'fetchActivityDiscontStatus'
/*GETTER_NAMES*/
export const GET_STUDENTFOR_DA = 'getStudentForDiscontActivity'
export const GET_ACTIVITY_STUDENTS_GB = 'getActivityDiscontStudentGP'
export const GET_ACTIVITY_GRADES_DP = 'getActivitiyGraderPeriods'
export const GET_ACTIVITIY_GRADES_D = 'getActivityGradesD'
export const GET_STUDENT_FOR_D = 'getStudentForD'
export const GET_DISCONT = 'getDıscont'
export const GET_DISCONT_HEADER = 'getDıscontHeader'
export const GET_SELECTEDPROGRAM_STUDENTS = 'getSelectedProgramStudents'
export const GET_DISCONT_STUDENTS = 'getDiscontStudents'
/*MUTATIONS_NAMES*/
export const SET_STUDENT_ACTIVITY_FORA = 'setActivityStudentForDA'
export const SET_ACTIVITIY_STUDENT_DP = 'setActivityStudentDP'
export const SET_ACTIVITY_GRADERS_DP = 'setActivitiyGraderPeriods'
export const SET_ACTIVITIY_GRADES_D = 'setActivityGradesD'
export const SET_STUDENT_FOR_D = 'setStudentForD'
export const SET_DISCONT_STUDENTS_LISTS = 'setDiscontStudents'
export const SET_DISCONT = 'setDıscont'
export const SET_SELECTEDPROGRAM_STUDENTS = 'setSelectedProgramStudents'
