/*ACTION_NAMES*/

export const FETCH_POST = 'fetchPost'
export const CREATE_POST = 'createPost'
export const DELETE_POST = 'deletePost'
export const UPDATE_POST = 'updatePost'
export const FETCH_ALL_POST = 'fetchAllPost'
export const FETCH_NEXT_POST = 'fetchNextPage'
export const LIKE_POST = 'likePost'
export const FETCH_POST_LIKE_USER = 'fetchPostLikeUsers'
export const FETCH_USER_POST = 'fetchUserPost'
export const FETCH_NEXT_USERS_POST = 'fetchNextUsersPost'
export const FETCH_POST_VIEW_USER = 'fetchPostViewUsers'
export const FETCH_POST_DETAIL = 'fetchPostDetail'
export const LIKE_COMMENT = 'likeComment'
export const DELETE_COMMENT = 'deleteComment'
export const CREATE_COMMENT = 'createComment'
export const FETCH_POST_COMMENT = 'getcomments'
/*GETTER_NAMES*/
export const GET_POST_DETAIL_PASS_DATA = 'getPostDetailPassedData'
export const GET_POST_VIEW_USER = 'getPostViewUser'
export const GET_USER_POST = 'getUserPost'
export const GET_POST_LIKE_USER = 'getPostLikeUser'
export const GET_POST = 'getPost'
export const GET_POST_HEADER = 'getPostHeader'

/*MUTATIONS_NAMES*/
export const SET_POST_DETAIL_PASS_DATA = 'setPostDetailPassedData'
export const SET_VIEW_POST_USER = 'setPostViewUser'
export const SET_NEXT_USERS_POST = 'setNextUsersPost'
export const SET_USER_POST = 'setUserPost'
export const SET_POST_LIKE_USER = 'setPostLikeUser'
export const SET_POST = 'setPost'
export const SET_NEXT_POST = 'setNextPost'
